spring:
  datasource:
    url: jdbc:mysql://${db_host:localhost}:${db_port:3306}/${db_name:demo}?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: ${db_username:root}
    password: ${db_password:root}
    driverClassName: com.mysql.jdbc.Driver
  profiles:
    include:
      - mybatis